[package]
name = "minijinja-include-loop-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = { version = "2.0.3", features = ["loader"] }
serde = { version = "1.0.204", features = ["derive"] }
